from __future__ import annotations

# Built-in curated model catalog for EDMG Studio.
# NOTE: We intentionally do NOT bundle large weights in the installer.
# The catalog drives the GUI "Model Manager" which downloads models on-demand.

from typing import Any


def _entry(
    *,
    model_id: str,
    name: str,
    kind: str,
    source: str,
    license_id: str,
    license_url: str,
    recommended: str,
    notes: str,
    installable: bool = True,
    redistributable_in_installer: bool = False,
    **extra: Any,
) -> dict[str, Any]:
    entry: dict[str, Any] = {
        "id": model_id,
        "name": name,
        "kind": kind,
        "source": source,
        "license_id": license_id,
        "license_url": license_url,
        "redistributable_in_installer": redistributable_in_installer,
        "recommended": recommended,
        "installable": installable,
        "notes": notes,
    }
    entry.update(extra)
    return entry


def built_in_catalog() -> list[dict[str, Any]]:
    # Fields:
    # - id: stable ID
    # - name: display name
    # - kind: llm | checkpoint | diffusers | controlnet | motion_module | runtime_bundle
    # - source: ollama | hf | civitai | local | s3
    # - installable: whether Studio can install this entry directly
    # - target: installation instructions (where it goes)
    # - render: optional UI/runtime metadata for Render page presets
    # - collections / tags / hardware_targets: discovery metadata for the richer Hub browser
    return [
        _entry(
            model_id="ollama_qwen3_4b",
            name="Qwen3 4B (Ollama)",
            kind="llm",
            source="ollama",
            ollama_model="qwen3:4b",
            license_id="Apache-2.0",
            license_url="https://huggingface.co/Qwen/Qwen3-4B",
            recommended="advanced",
            notes="Low-resource local planner fallback for CPU-only or low-memory systems.",
            tags=["planning", "local", "fallback", "lightweight"],
        ),
        _entry(
            model_id="ollama_qwen3_8b",
            name="Qwen3 8B (Ollama)",
            kind="llm",
            source="ollama",
            ollama_model="qwen3:8b",
            license_id="Apache-2.0",
            license_url="https://huggingface.co/Qwen/Qwen3-8B",
            recommended="default",
            notes="Recommended local planner default for offline Studio workflows on capable systems.",
            tags=["planning", "local", "default", "quality"],
        ),
        _entry(
            model_id="ollama_qwen2p5_3b_instruct",
            name="Qwen2.5 3B Instruct (Ollama)",
            kind="llm",
            source="ollama",
            ollama_model="qwen2.5:3b-instruct",
            license_id="Apache-2.0",
            license_url="https://huggingface.co/Qwen/Qwen2.5-3B-Instruct",
            recommended="advanced",
            notes="Legacy light planner retained for existing installs that still depend on the Qwen2.5 tag.",
            tags=["planning", "local", "legacy", "lightweight"],
        ),
        _entry(
            model_id="ollama_qwen2p5_7b_instruct",
            name="Qwen2.5 7B Instruct (Ollama)",
            kind="llm",
            source="ollama",
            ollama_model="qwen2.5:7b-instruct",
            license_id="Apache-2.0",
            license_url="https://huggingface.co/Qwen/Qwen2.5-7B-Instruct",
            recommended="advanced",
            notes="Legacy higher-quality planner retained for compatibility with existing Qwen2.5 setups.",
            tags=["planning", "local", "legacy", "quality"],
        ),
        _entry(
            model_id="hf_sd15_internal",
            name="Stable Diffusion v1.5 (Internal / Diffusers)",
            kind="diffusers",
            source="hf",
            hf_repo_id="runwayml/stable-diffusion-v1-5",
            target={"engine": "internal", "folder": "diffusers"},
            license_id="openrail-m",
            license_url="https://huggingface.co/runwayml/stable-diffusion-v1-5",
            recommended="default",
            notes="CPU-friendlier internal fallback for proxy-safe video rendering and previews.",
            family="sd15",
            author="runwayml",
            tags=["internal", "video", "fallback"],
            hardware_targets=["cpu", "integrated_gpu", "discrete_gpu"],
            render={
                "engine": "internal",
                "workflow_family": "diffusers",
                "render_modes": ["internal_video"],
                "preferred_for": ["fallback", "draft", "laptop"],
            },
        ),
        _entry(
            model_id="hf_sdxl_internal",
            name="Stable Diffusion XL Base 1.0 (Internal / Diffusers)",
            kind="diffusers",
            source="hf",
            hf_repo_id="stabilityai/stable-diffusion-xl-base-1.0",
            target={"engine": "internal", "folder": "diffusers"},
            license_id="openrail++",
            license_url="https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/blob/main/LICENSE.md",
            recommended="advanced",
            notes="Balanced internal renderer for GPU-backed video work.",
            family="sdxl",
            author="stabilityai",
            collections=["image", "stabilityais-sdxl-models"],
            tags=["internal", "video", "sdxl"],
            hardware_targets=["discrete_gpu", "apple_silicon"],
            render={
                "engine": "internal",
                "workflow_family": "diffusers",
                "render_modes": ["internal_video"],
                "preferred_for": ["balanced", "quality"],
            },
        ),
        _entry(
            model_id="hf_sd35_medium_internal",
            name="Stable Diffusion 3.5 Medium (Internal / Diffusers)",
            kind="diffusers",
            source="hf",
            hf_repo_id="stabilityai/stable-diffusion-3.5-medium",
            target={"engine": "internal", "folder": "diffusers"},
            license_id="stability-ai-community",
            license_url="https://huggingface.co/stabilityai/stable-diffusion-3.5-medium/blob/main/LICENSE.md",
            recommended="advanced",
            notes="Higher-prompt-adherence internal renderer for stronger GPUs. Best internal SD3.5 path inside Studio.",
            family="sd35",
            author="stabilityai",
            collections=["stable-diffusion-35", "stable-diffusion-3"],
            tags=["internal", "video", "sd35"],
            hardware_targets=["discrete_gpu"],
            render={
                "engine": "internal",
                "workflow_family": "diffusers",
                "render_modes": ["internal_video"],
                "preferred_for": ["quality", "sd35"],
            },
        ),
        _entry(
            model_id="hf_sd15_controlnet_canny_internal",
            name="ControlNet Canny SD 1.5 (Internal / Diffusers)",
            kind="controlnet",
            source="hf",
            hf_repo_id="lllyasviel/control_v11p_sd15_canny",
            target={"engine": "internal", "folder": "controlnet"},
            license_id="openrail",
            license_url="https://huggingface.co/lllyasviel/control_v11p_sd15_canny",
            recommended="advanced",
            notes="Curated internal ControlNet for SD 1.5 edge-guided still generation.",
            family="sd15",
            author="lllyasviel",
            tags=["internal", "controlnet", "sd15", "canny"],
            hardware_targets=["cpu", "integrated_gpu", "discrete_gpu"],
            render={
                "engine": "internal",
                "workflow_family": "controlnet",
                "render_modes": ["stills"],
                "conditioning_mode": "edge",
            },
        ),
        _entry(
            model_id="hf_sd15_controlnet_depth_internal",
            name="ControlNet Depth SD 1.5 (Internal / Diffusers)",
            kind="controlnet",
            source="hf",
            hf_repo_id="lllyasviel/control_v11f1p_sd15_depth",
            target={"engine": "internal", "folder": "controlnet"},
            license_id="openrail",
            license_url="https://huggingface.co/lllyasviel/control_v11f1p_sd15_depth",
            recommended="advanced",
            notes="Curated internal ControlNet for SD 1.5 depth-guided still generation.",
            family="sd15",
            author="lllyasviel",
            tags=["internal", "controlnet", "sd15", "depth"],
            hardware_targets=["cpu", "integrated_gpu", "discrete_gpu"],
            render={
                "engine": "internal",
                "workflow_family": "controlnet",
                "render_modes": ["stills"],
                "conditioning_mode": "external",
            },
        ),
        _entry(
            model_id="hf_sdxl_controlnet_canny_internal",
            name="ControlNet Canny SDXL (Internal / Diffusers)",
            kind="controlnet",
            source="hf",
            hf_repo_id="diffusers/controlnet-canny-sdxl-1.0",
            target={"engine": "internal", "folder": "controlnet"},
            license_id="openrail++",
            license_url="https://huggingface.co/diffusers/controlnet-canny-sdxl-1.0",
            recommended="advanced",
            notes="Curated internal ControlNet for SDXL edge-guided still generation.",
            family="sdxl",
            author="diffusers",
            tags=["internal", "controlnet", "sdxl", "canny"],
            hardware_targets=["discrete_gpu", "apple_silicon"],
            render={
                "engine": "internal",
                "workflow_family": "controlnet",
                "render_modes": ["stills"],
                "conditioning_mode": "edge",
            },
        ),
        _entry(
            model_id="hf_sdxl_controlnet_depth_internal",
            name="ControlNet Depth SDXL (Internal / Diffusers)",
            kind="controlnet",
            source="hf",
            hf_repo_id="diffusers/controlnet-depth-sdxl-1.0",
            target={"engine": "internal", "folder": "controlnet"},
            license_id="openrail++",
            license_url="https://huggingface.co/diffusers/controlnet-depth-sdxl-1.0",
            recommended="advanced",
            notes="Curated internal ControlNet for SDXL depth-guided still generation.",
            family="sdxl",
            author="diffusers",
            tags=["internal", "controlnet", "sdxl", "depth"],
            hardware_targets=["discrete_gpu", "apple_silicon"],
            render={
                "engine": "internal",
                "workflow_family": "controlnet",
                "render_modes": ["stills"],
                "conditioning_mode": "external",
            },
        ),
        _entry(
            model_id="hf_sdxl_base_1_0",
            name="Stable Diffusion XL Base 1.0 (Checkpoint)",
            kind="checkpoint",
            source="hf",
            hf_url="https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors",
            filename="sd_xl_base_1.0.safetensors",
            target={"engine": "comfyui", "folder": "checkpoints"},
            license_id="openrail++",
            license_url="https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/blob/main/LICENSE.md",
            recommended="default",
            notes="Broadly compatible ComfyUI baseline checkpoint and the default still-image lane inside Studio.",
            family="sdxl",
            author="stabilityai",
            collections=["image", "stabilityais-sdxl-models"],
            tags=["comfyui", "stills", "baseline"],
            hardware_targets=["integrated_gpu", "discrete_gpu"],
            render={
                "engine": "comfyui",
                "workflow_family": "txt2img",
                "render_modes": ["stills", "motion_ad"],
                "checkpoint_name": "sd_xl_base_1.0.safetensors",
            },
        ),
        _entry(
            model_id="hf_sdxl_refiner_1_0",
            name="Stable Diffusion XL Refiner 1.0 (Checkpoint)",
            kind="checkpoint",
            source="hf",
            hf_url="https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/resolve/main/sd_xl_refiner_1.0.safetensors",
            filename="sd_xl_refiner_1.0.safetensors",
            target={"engine": "comfyui", "folder": "checkpoints"},
            license_id="openrail++",
            license_url="https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/blob/main/LICENSE.md",
            recommended="advanced",
            notes="Optional second-pass enhancement checkpoint; heavy VRAM use.",
            family="sdxl",
            author="stabilityai",
            collections=["image", "stabilityais-sdxl-models"],
            tags=["comfyui", "stills", "refiner"],
            hardware_targets=["discrete_gpu"],
            render={
                "engine": "comfyui",
                "workflow_family": "txt2img",
                "render_modes": ["stills"],
                "checkpoint_name": "sd_xl_refiner_1.0.safetensors",
            },
        ),
        _entry(
            model_id="hf_sd35_medium_ckpt",
            name="Stable Diffusion 3.5 Medium (Checkpoint)",
            kind="checkpoint",
            source="hf",
            hf_url="https://huggingface.co/stabilityai/stable-diffusion-3.5-medium/resolve/main/sd3.5_medium.safetensors",
            filename="sd3.5_medium.safetensors",
            target={"engine": "comfyui", "folder": "checkpoints"},
            license_id="stability-ai-community",
            license_url="https://huggingface.co/stabilityai/stable-diffusion-3.5-medium/blob/main/LICENSE.md",
            recommended="advanced",
            notes="Curated SD3.5 image checkpoint for ComfyUI still rendering.",
            family="sd35",
            author="stabilityai",
            collections=["stable-diffusion-35", "stable-diffusion-3"],
            tags=["comfyui", "stills", "sd35"],
            hardware_targets=["discrete_gpu"],
            render={
                "engine": "comfyui",
                "workflow_family": "txt2img",
                "render_modes": ["stills"],
                "checkpoint_name": "sd3.5_medium.safetensors",
            },
        ),
        _entry(
            model_id="hf_sd35_large_ckpt",
            name="Stable Diffusion 3.5 Large (Checkpoint)",
            kind="checkpoint",
            source="hf",
            hf_url="https://huggingface.co/stabilityai/stable-diffusion-3.5-large/resolve/main/sd3.5_large.safetensors",
            filename="sd3.5_large.safetensors",
            target={"engine": "comfyui", "folder": "checkpoints"},
            license_id="stability-ai-community",
            license_url="https://huggingface.co/stabilityai/stable-diffusion-3.5-large/blob/main/LICENSE.md",
            recommended="advanced",
            notes="Highest-quality SD3.5 still checkpoint for stronger ComfyUI GPUs.",
            family="sd35",
            author="stabilityai",
            collections=["stable-diffusion-35", "stable-diffusion-3"],
            tags=["comfyui", "stills", "sd35", "quality"],
            hardware_targets=["discrete_gpu"],
            render={
                "engine": "comfyui",
                "workflow_family": "txt2img",
                "render_modes": ["stills"],
                "checkpoint_name": "sd3.5_large.safetensors",
            },
        ),
        _entry(
            model_id="hf_sd35_large_turbo_ckpt",
            name="Stable Diffusion 3.5 Large Turbo (Checkpoint)",
            kind="checkpoint",
            source="hf",
            hf_url="https://huggingface.co/stabilityai/stable-diffusion-3.5-large-turbo/resolve/main/sd3.5_large_turbo.safetensors",
            filename="sd3.5_large_turbo.safetensors",
            target={"engine": "comfyui", "folder": "checkpoints"},
            license_id="stability-ai-community",
            license_url="https://huggingface.co/stabilityai/stable-diffusion-3.5-large-turbo/blob/main/LICENSE.md",
            recommended="advanced",
            notes="Fast higher-quality SD3.5 still checkpoint for Studio's accelerated ComfyUI lane.",
            family="sd35",
            author="stabilityai",
            collections=["stable-diffusion-35", "stable-diffusion-3"],
            tags=["comfyui", "stills", "sd35", "turbo"],
            hardware_targets=["discrete_gpu"],
            render={
                "engine": "comfyui",
                "workflow_family": "txt2img",
                "render_modes": ["stills"],
                "checkpoint_name": "sd3.5_large_turbo.safetensors",
            },
        ),
        _entry(
            model_id="hf_sd35_controlnet_blur",
            name="SD3.5 Large ControlNet Blur",
            kind="controlnet",
            source="hf",
            hf_url="https://huggingface.co/stabilityai/stable-diffusion-3.5-controlnets/resolve/main/sd3.5_large_controlnet_blur.safetensors",
            filename="sd3.5_large_controlnet_blur.safetensors",
            target={"engine": "comfyui", "folder": "controlnet"},
            license_id="stability-ai-community",
            license_url="https://huggingface.co/stabilityai/stable-diffusion-3.5-controlnets/blob/main/LICENSE.md",
            recommended="advanced",
            notes="Most seamless SD3.5 ControlNet option for reference-driven composition in Studio.",
            family="sd35",
            author="stabilityai",
            collections=["stable-diffusion-35", "image"],
            tags=["comfyui", "controlnet", "sd35", "reference"],
            hardware_targets=["discrete_gpu"],
            render={
                "engine": "comfyui",
                "workflow_family": "controlnet",
                "render_modes": ["stills"],
                "checkpoint_name": "sd3.5_large_turbo.safetensors",
                "controlnet_name": "sd3.5_large_controlnet_blur.safetensors",
                "conditioning_mode": "blur",
            },
        ),
        _entry(
            model_id="hf_sd35_controlnet_canny",
            name="SD3.5 Large ControlNet Canny",
            kind="controlnet",
            source="hf",
            hf_url="https://huggingface.co/stabilityai/stable-diffusion-3.5-controlnets/resolve/main/sd3.5_large_controlnet_canny.safetensors",
            filename="sd3.5_large_controlnet_canny.safetensors",
            target={"engine": "comfyui", "folder": "controlnet"},
            license_id="stability-ai-community",
            license_url="https://huggingface.co/stabilityai/stable-diffusion-3.5-controlnets/blob/main/LICENSE.md",
            recommended="advanced",
            notes="Use with edge-style reference inputs for structure-preserving SD3.5 stills.",
            family="sd35",
            author="stabilityai",
            collections=["stable-diffusion-35", "image"],
            tags=["comfyui", "controlnet", "sd35", "edges"],
            hardware_targets=["discrete_gpu"],
            render={
                "engine": "comfyui",
                "workflow_family": "controlnet",
                "render_modes": ["stills"],
                "checkpoint_name": "sd3.5_large_turbo.safetensors",
                "controlnet_name": "sd3.5_large_controlnet_canny.safetensors",
                "conditioning_mode": "edge",
            },
        ),
        _entry(
            model_id="hf_sd35_controlnet_depth",
            name="SD3.5 Large ControlNet Depth",
            kind="controlnet",
            source="hf",
            hf_url="https://huggingface.co/stabilityai/stable-diffusion-3.5-controlnets/resolve/main/sd3.5_large_controlnet_depth.safetensors",
            filename="sd3.5_large_controlnet_depth.safetensors",
            target={"engine": "comfyui", "folder": "controlnet"},
            license_id="stability-ai-community",
            license_url="https://huggingface.co/stabilityai/stable-diffusion-3.5-controlnets/blob/main/LICENSE.md",
            recommended="advanced",
            notes="Use when you already have a prepared depth-style conditioning image.",
            family="sd35",
            author="stabilityai",
            collections=["stable-diffusion-35", "image"],
            tags=["comfyui", "controlnet", "sd35", "depth"],
            hardware_targets=["discrete_gpu"],
            render={
                "engine": "comfyui",
                "workflow_family": "controlnet",
                "render_modes": ["stills"],
                "checkpoint_name": "sd3.5_large_turbo.safetensors",
                "controlnet_name": "sd3.5_large_controlnet_depth.safetensors",
                "conditioning_mode": "external",
            },
        ),
        _entry(
            model_id="hf_svd_xt_1_1",
            name="Stable Video Diffusion XT 1.1",
            kind="motion_module",
            source="hf",
            hf_url="https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt-1-1/resolve/main/svd_xt_1_1.safetensors",
            filename="svd_xt_1_1.safetensors",
            target={"engine": "comfyui", "folder": "checkpoints"},
            license_id="stability-ai-community",
            license_url="https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt-1-1/blob/main/LICENSE.md",
            recommended="advanced",
            notes="Curated image-to-video checkpoint for Studio's ComfyUI SVD motion path.",
            family="svd",
            author="stabilityai",
            collections=["video"],
            tags=["comfyui", "video", "svd"],
            hardware_targets=["discrete_gpu"],
            render={
                "engine": "comfyui",
                "workflow_family": "svd",
                "render_modes": ["motion_svd"],
                "svd_checkpoint": "svd_xt_1_1.safetensors",
                "checkpoint_name": "sd3.5_large_turbo.safetensors",
            },
        ),
        _entry(
            model_id="hf_sd35_large_tensorrt_bundle",
            name="Stable Diffusion 3.5 Large TensorRT Bundle",
            kind="runtime_bundle",
            source="hf",
            hf_repo_id="stabilityai/stable-diffusion-3.5-large-tensorrt",
            target={"engine": "runtime_bundle", "folder": "tensorrt"},
            license_id="stability-ai-community",
            license_url="https://huggingface.co/stabilityai/stable-diffusion-3.5-large-tensorrt/blob/main/LICENSE.md",
            recommended="advanced",
            installable=False,
            notes="NVIDIA-optimized runtime bundle. Surfaced in Studio for discovery, but Studio does not yet run TensorRT image jobs natively.",
            family="sd35",
            author="stabilityai",
            collections=["nvidia-optimized", "stable-diffusion-35"],
            tags=["browser_only", "nvidia", "tensorrt"],
            hardware_targets=["nvidia"],
        ),
        _entry(
            model_id="hf_sd35_controlnets_tensorrt_bundle",
            name="SD3.5 ControlNets TensorRT Bundle",
            kind="runtime_bundle",
            source="hf",
            hf_repo_id="stabilityai/stable-diffusion-3.5-controlnets-tensorrt",
            target={"engine": "runtime_bundle", "folder": "tensorrt"},
            license_id="stability-ai-community",
            license_url="https://huggingface.co/stabilityai/stable-diffusion-3.5-controlnets-tensorrt/blob/main/LICENSE.md",
            recommended="advanced",
            installable=False,
            notes="NVIDIA-optimized SD3.5 ControlNet bundle. Browser-only in this pass until Studio grows a TensorRT execution path.",
            family="sd35",
            author="stabilityai",
            collections=["nvidia-optimized", "stable-diffusion-35"],
            tags=["browser_only", "nvidia", "tensorrt", "controlnet"],
            hardware_targets=["nvidia"],
        ),
        _entry(
            model_id="hf_svd_xt_1_1_tensorrt_bundle",
            name="SVD XT 1.1 TensorRT Bundle",
            kind="runtime_bundle",
            source="hf",
            hf_repo_id="stabilityai/stable-video-diffusion-img2vid-xt-1-1-tensorrt",
            target={"engine": "runtime_bundle", "folder": "tensorrt"},
            license_id="other",
            license_url="https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt-1-1-tensorrt",
            recommended="advanced",
            installable=False,
            notes="NVIDIA-optimized SVD runtime. Surfaced for discovery while Studio keeps the standard SVD checkpoint path.",
            family="svd",
            author="stabilityai",
            collections=["nvidia-optimized", "video"],
            tags=["browser_only", "nvidia", "tensorrt", "video"],
            hardware_targets=["nvidia"],
        ),
        _entry(
            model_id="hf_sd35_large_amdgpu_bundle",
            name="Stable Diffusion 3.5 Large AMDGPU Bundle",
            kind="runtime_bundle",
            source="hf",
            hf_repo_id="stabilityai/stable-diffusion-3.5-large_amdgpu",
            target={"engine": "runtime_bundle", "folder": "amd"},
            license_id="stability-ai-community",
            license_url="https://huggingface.co/stabilityai/stable-diffusion-3.5-large_amdgpu/blob/main/LICENSE.md",
            recommended="advanced",
            installable=False,
            notes="AMD-optimized package. Studio surfaces it in the Hub browser while the DirectML execution path is still separate from the main renderer.",
            family="sd35",
            author="stabilityai",
            collections=["amd-optimized", "stable-diffusion-35"],
            tags=["browser_only", "amd", "directml"],
            hardware_targets=["amd", "windows"],
        ),
    ]


def built_in_packs() -> list[dict[str, Any]]:
    # Packs used by first-run wizard and Model Manager.
    return [
        {
            "id": "basic",
            "name": "Basic (Planning + Preflight)",
            "description": "Installs the default Qwen3 8B Ollama planner. Use this if you only want planning, ingest, and preflight right now.",
            "models": ["ollama_qwen3_8b"],
        },
        {
            "id": "creator",
            "name": "Creator (Recommended)",
            "description": "Installs the default Qwen3 8B Ollama planner plus SDXL Base for broadly compatible ComfyUI still rendering.",
            "models": ["ollama_qwen3_8b", "hf_sdxl_base_1_0"],
        },
        {
            "id": "stability_sd35",
            "name": "Stability SD3.5 Image Lab",
            "description": "Adds Studio's curated SD3.5 still stack: Large Turbo plus Blur/Canny/Depth ControlNets for reference-driven renders.",
            "models": [
                "ollama_qwen3_8b",
                "hf_sd35_large_turbo_ckpt",
                "hf_sd35_controlnet_blur",
                "hf_sd35_controlnet_canny",
                "hf_sd35_controlnet_depth",
            ],
        },
        {
            "id": "stability_motion",
            "name": "Stability Motion Lab",
            "description": "Adds the curated SVD XT image-to-video fallback on top of the SD3.5 turbo still path.",
            "models": [
                "ollama_qwen3_8b",
                "hf_sd35_large_turbo_ckpt",
                "hf_svd_xt_1_1",
            ],
        },
        {
            "id": "pro",
            "name": "Pro (Advanced)",
            "description": "Adds higher-quality internal and ComfyUI renderers: SDXL internal, SD3.5 medium internal, SD3.5 large, and the SDXL refiner.",
            "models": [
                "ollama_qwen3_8b",
                "hf_sdxl_base_1_0",
                "hf_sdxl_internal",
                "hf_sd35_medium_internal",
                "hf_sd35_large_ckpt",
                "hf_sdxl_refiner_1_0",
            ],
        },
    ]
