param(
  [string]$IsccExe = "",
  [string]$OutputDirectory = "dist-winui"
)

$ErrorActionPreference = "Stop"

function Resolve-InnoCompiler([string]$RequestedPath) {
  if ($RequestedPath) {
    if (Test-Path -LiteralPath $RequestedPath -PathType Leaf) {
      return (Resolve-Path -LiteralPath $RequestedPath).Path
    }
    throw "Inno Setup compiler not found: $RequestedPath"
  }

  $programRoots = @($env:ProgramFiles, ${env:ProgramFiles(x86)}) |
    Where-Object { -not [string]::IsNullOrWhiteSpace($_) } |
    Select-Object -Unique
  $candidates = @(
    $programRoots | ForEach-Object { Join-Path $_ "Inno Setup 7\ISCC.exe" }
    if ($env:LOCALAPPDATA) { Join-Path $env:LOCALAPPDATA "Programs\Inno Setup 7\ISCC.exe" }
  )
  foreach ($candidate in $candidates) {
    if (Test-Path -LiteralPath $candidate -PathType Leaf) {
      return $candidate
    }
  }

  $command = Get-Command "ISCC.exe" -ErrorAction SilentlyContinue | Select-Object -First 1
  if ($command) {
    return $command.Source
  }
  throw "Inno Setup 7 was not found. Install it or pass -IsccExe <path-to-ISCC.exe>."
}

function Escape-InnoValue([string]$Value) {
  return $Value.Replace('"', '""')
}

function Get-Sha256Hex([string]$Path) {
  return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()
}

$studioDirectory = (Resolve-Path (Join-Path $PSScriptRoot "../..")).Path
$packageJson = Get-Content -Raw -LiteralPath (Join-Path $studioDirectory "package.json") | ConvertFrom-Json
$version = [string]$packageJson.version
$productName = [string]$packageJson.build.productName
if ([string]::IsNullOrWhiteSpace($productName)) { $productName = "EDMG Studio" }

$stageDirectory = Join-Path $studioDirectory "release\winui-msix"
$metadataPath = Join-Path $stageDirectory "winui-msix.json"
$managerPath = Join-Path $PSScriptRoot "manage_winui_package.ps1"
foreach ($requiredPath in @($metadataPath, $managerPath)) {
  if (-not (Test-Path -LiteralPath $requiredPath -PathType Leaf)) {
    throw "Required WinUI installer input was not found: $requiredPath"
  }
}

$metadata = Get-Content -Raw -LiteralPath $metadataPath | ConvertFrom-Json
if ([int]$metadata.schemaVersion -ne 1 -or
    [string]$metadata.package.architecture -cne "x64" -or
    [string]$metadata.package.applicationId -cne "App" -or
    [string]$metadata.package.windowsAppSdkDeployment -cne "self-contained") {
  throw "Staged WinUI metadata does not describe a supported self-contained x64 package."
}

$msixPath = Join-Path $stageDirectory ([string]$metadata.package.fileName)
if (-not (Test-Path -LiteralPath $msixPath -PathType Leaf)) {
  throw "Staged WinUI package was not found: $msixPath"
}
if ((Get-Sha256Hex $msixPath) -cne ([string]$metadata.package.sha256).ToLowerInvariant()) {
  throw "Staged WinUI package bytes do not match winui-msix.json."
}

$signature = Get-AuthenticodeSignature -LiteralPath $msixPath
if ($signature.Status -ne [Management.Automation.SignatureStatus]::Valid) {
  throw "The WinUI package must be signed by a trusted certificate before building its installer (status: $($signature.Status))."
}

Add-Type -AssemblyName System.IO.Compression.FileSystem
$archive = [IO.Compression.ZipFile]::OpenRead($msixPath)
try {
  $entryNames = @($archive.Entries | ForEach-Object { $_.FullName.Replace("\", "/") })
  foreach ($requiredEntry in @(
    "AppxManifest.xml",
    "backend/edmg-studio-backend.exe",
    "backend/backend-bundle-manifest.json",
    "bin/ffmpeg.exe",
    "bin/ffprobe.exe"
  )) {
    if ($requiredEntry -cnotin $entryNames) {
      throw "The staged WinUI package is not self-contained; missing $requiredEntry."
    }
  }
  if (-not ($entryNames | Where-Object { $_ -like "backend/_internal/*" } | Select-Object -First 1)) {
    throw "The staged WinUI package is missing the backend runtime directory."
  }
} finally {
  $archive.Dispose()
}

if ([IO.Path]::IsPathRooted($OutputDirectory)) {
  $outputPath = [IO.Path]::GetFullPath($OutputDirectory)
} else {
  $outputPath = [IO.Path]::GetFullPath((Join-Path $studioDirectory $OutputDirectory))
}
New-Item -ItemType Directory -Force -Path $outputPath | Out-Null

$outputBaseName = "EDMG-Studio-$version-windows-x64-Setup"
$generatedScript = Join-Path $outputPath "edmg-studio-winui.iss"
$iconPath = Join-Path $studioDirectory "electron-resources\app-icon.ico"
$msixHash = Get-Sha256Hex $msixPath
$lines = @(
  "; Generated by packaging/windows/build_winui_installer.ps1. Do not edit.",
  "",
  "#if VER < EncodeVer(7,0,0)",
  "  #error Inno Setup 7 or newer is required",
  "#endif",
  "",
  "[Setup]",
  "AppId={{faa597b4-33fe-5e5f-81a9-4db216782ca3}",
  ("AppName={0}" -f (Escape-InnoValue $productName)),
  ("AppVersion={0}" -f (Escape-InnoValue $version)),
  "AppPublisher=Dwct",
  "AppPublisherURL=https://github.com/DWCTEDMG/DWCTGenerativeSoundStudio",
  "AppSupportURL=https://github.com/DWCTEDMG/DWCTGenerativeSoundStudio/issues",
  ("DefaultDirName={{localappdata}}\Programs\{0}" -f (Escape-InnoValue $productName)),
  ("DefaultGroupName={0}" -f (Escape-InnoValue $productName)),
  ("OutputDir={0}" -f (Escape-InnoValue $outputPath)),
  ("OutputBaseFilename={0}" -f (Escape-InnoValue $outputBaseName)),
  "Compression=lzma2/max",
  "SolidCompression=yes",
  "WizardStyle=modern",
  "PrivilegesRequired=lowest",
  "ArchitecturesAllowed=x64compatible",
  "ArchitecturesInstallIn64BitMode=x64compatible",
  "DisableProgramGroupPage=yes",
  "CloseApplications=yes"
)
if (Test-Path -LiteralPath $iconPath -PathType Leaf) {
  $lines += ("SetupIconFile={0}" -f (Escape-InnoValue $iconPath))
}

$lines += @(
  "",
  "[Files]",
  ('Source: "{0}"; DestDir: "{{app}}\package"; DestName: "{1}"; Hash: "{2}"; Flags: ignoreversion' -f (Escape-InnoValue $msixPath), (Escape-InnoValue ([IO.Path]::GetFileName($msixPath))), $msixHash),
  ('Source: "{0}"; DestDir: "{{app}}\package"; DestName: "manage_winui_package.ps1"; Flags: ignoreversion' -f (Escape-InnoValue $managerPath)),
  "",
  "[Icons]",
  'Name: "{group}\EDMG Studio"; Filename: "{sys}\WindowsPowerShell\v1.0\powershell.exe"; Parameters: "-NoProfile -NonInteractive -ExecutionPolicy Bypass -WindowStyle Hidden -File ""{app}\package\manage_winui_package.ps1"" -Action Launch"',
  'Name: "{userdesktop}\EDMG Studio"; Filename: "{sys}\WindowsPowerShell\v1.0\powershell.exe"; Parameters: "-NoProfile -NonInteractive -ExecutionPolicy Bypass -WindowStyle Hidden -File ""{app}\package\manage_winui_package.ps1"" -Action Launch"; Tasks: desktopicon',
  "",
  "[Tasks]",
  'Name: "desktopicon"; Description: "Create a desktop shortcut"; GroupDescription: "Additional shortcuts:"; Flags: unchecked',
  "",
  "[Run]",
  ('Filename: "{{sys}}\WindowsPowerShell\v1.0\powershell.exe"; Parameters: "-NoProfile -NonInteractive -ExecutionPolicy Bypass -WindowStyle Hidden -File ""{{app}}\package\manage_winui_package.ps1"" -Action Install -MsixPath ""{{app}}\package\{0}"""; StatusMsg: "Installing EDMG Studio..."; Flags: runhidden waituntilterminated' -f (Escape-InnoValue ([IO.Path]::GetFileName($msixPath)))),
  'Filename: "{sys}\WindowsPowerShell\v1.0\powershell.exe"; Parameters: "-NoProfile -NonInteractive -ExecutionPolicy Bypass -WindowStyle Hidden -File ""{app}\package\manage_winui_package.ps1"" -Action Launch"; Description: "Launch EDMG Studio"; Flags: nowait postinstall skipifsilent',
  "",
  "[UninstallRun]",
  'Filename: "{sys}\WindowsPowerShell\v1.0\powershell.exe"; Parameters: "-NoProfile -NonInteractive -ExecutionPolicy Bypass -WindowStyle Hidden -File ""{app}\package\manage_winui_package.ps1"" -Action Uninstall"; RunOnceId: "RemoveEdmgStudioWinUi"; Flags: runhidden waituntilterminated'
)
[IO.File]::WriteAllLines($generatedScript, $lines, [Text.UTF8Encoding]::new($true))

$iscc = Resolve-InnoCompiler $IsccExe
& $iscc $generatedScript
if ($LASTEXITCODE -ne 0) {
  throw "Inno Setup compilation failed with exit code $LASTEXITCODE."
}

$setupPath = Join-Path $outputPath ($outputBaseName + ".exe")
if (-not (Test-Path -LiteralPath $setupPath -PathType Leaf)) {
  throw "Inno Setup completed but did not produce $setupPath."
}

$signingScript = Join-Path $PSScriptRoot "sign_release.ps1"
if (-not [string]::IsNullOrWhiteSpace([string]$env:EDMG_CODE_SIGN_CERT)) {
  & powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $signingScript `
    -StudioDir $studioDirectory -ArtifactPaths $setupPath -RequireSigning
  if ($LASTEXITCODE -ne 0) {
    throw "Setup executable signing failed with exit code $LASTEXITCODE."
  }
}

Write-Host "WinUI installer created: $setupPath" -ForegroundColor Green
