FROM node:22-bookworm-slim AS web-build

WORKDIR /app

RUN corepack enable

COPY . .

RUN pnpm install --no-frozen-lockfile
RUN pnpm run build


FROM nginx:1.27-alpine

COPY deployment/starlift/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=web-build /app/dist-web /usr/share/nginx/html

EXPOSE 8080
