import type { StudioForgeRecipe } from "./types";

export const STUDIO_FORGE_RECIPES: StudioForgeRecipe[] = [
  {
    id: "audio-analysis-plan-render-assemble",
    name: "Audio -> Analysis -> AI Plan -> Render -> Assemble",
    description: "Tracks the default Studio path from source audio to finished video assembly while preserving the internal renderer as the default engine.",
    stages: [
      {
        id: "audio",
        label: "Audio ingest",
        description: "Select a project and attach its source track in Workspace.",
        destination: "workspace",
        requiredPrerequisites: ["project", "audio"],
      },
      {
        id: "analysis",
        label: "Analysis",
        description: "Build the saved music analysis used by planning and reactive controls.",
        destination: "workspace",
        requiredPrerequisites: ["analysis"],
      },
      {
        id: "plan",
        label: "AI plan",
        description: "Generate at least one valid visual plan variant.",
        destination: "workspace",
        requiredPrerequisites: ["plan"],
      },
      {
        id: "render",
        label: "Render and assemble",
        description: "Render through the canonical Render page and review the registered output.",
        destination: "render",
        requiredCapabilities: ["ffmpeg"],
        requiredPrerequisites: ["renderOutput"],
      },
    ],
    requiredCapabilities: ["backend", "internalRenderer", "ffmpeg"],
    optionalCapabilities: ["ollama", "edmgCore"],
    action: { label: "Continue workflow", destination: "workspace" },
    destructive: false,
    status: "supported",
  },
  {
    id: "still-image-workflow",
    name: "Still Image Workflow",
    description: "Preview a still-oriented recipe that can stay fully internal or branch to optional ComfyUI-backed workflows.",
    stages: [
      {
        id: "context",
        label: "Project context",
        description: "Select a project with analysis and a visual plan.",
        destination: "workspace",
        requiredPrerequisites: ["project", "analysis", "plan"],
      },
      {
        id: "model",
        label: "Local still model",
        description: "Install or restore a supported internal Diffusers model.",
        destination: "models",
        requiredCapabilities: ["internalRenderer"],
      },
      {
        id: "render",
        label: "Still render",
        description: "Launch and inspect the canonical internal render path.",
        destination: "render",
        requiredPrerequisites: ["renderOutput"],
      },
      {
        id: "review",
        label: "Review output",
        description: "Inspect the registered artifact and continuity metadata.",
        destination: "review",
        requiredPrerequisites: ["renderOutput"],
      },
    ],
    requiredCapabilities: ["backend", "internalRenderer"],
    optionalCapabilities: ["comfyui", "ollama"],
    requiredPrerequisites: ["project", "plan"],
    action: { label: "Continue still workflow", destination: "workspace" },
    destructive: false,
    status: "supported",
  },
  {
    id: "motion-workflow",
    name: "Motion Workflow",
    description: "Preview the steps for scene motion rendering while keeping ComfyUI motion as an additive sidecar rather than a required dependency.",
    stages: [
      {
        id: "plan",
        label: "Plan scenes",
        description: "Create a plan variant with scene timing and motion intent.",
        destination: "workspace",
        requiredPrerequisites: ["project", "plan"],
      },
      {
        id: "engine",
        label: "Pick a motion engine",
        description: "Use an internal motion adapter or the optional ComfyUI route.",
        destination: "models",
        anyCapabilities: ["internalMotion", "comfyMotion"],
      },
      {
        id: "render",
        label: "Render and assemble",
        description: "Queue motion clips and assemble them through Render.",
        destination: "render",
        requiredCapabilities: ["ffmpeg"],
        requiredPrerequisites: ["renderOutput"],
      },
      {
        id: "review",
        label: "Review output",
        description: "Review the completed artifact and any repair guidance.",
        destination: "review",
        requiredPrerequisites: ["renderOutput"],
      },
    ],
    requiredCapabilities: ["backend", "ffmpeg"],
    optionalCapabilities: ["comfyui", "internalRenderer"],
    requiredPrerequisites: ["project", "plan"],
    action: { label: "Continue motion workflow", destination: "workspace" },
    destructive: false,
    status: "supported",
  },
  {
    id: "deforum-export-workflow",
    name: "Deforum Export Workflow",
    description: "Preview how canonical Studio plans can end in an optional Deforum export without changing runtime defaults.",
    stages: [
      {
        id: "plan",
        label: "Plan variants",
        description: "Select a project and generate a plan variant.",
        destination: "workspace",
        requiredPrerequisites: ["project", "plan"],
      },
      {
        id: "direction",
        label: "Creative direction",
        description: "Review creative direction and motion schedules.",
        destination: "workspace",
        requiredPrerequisites: ["analysis", "plan"],
      },
      {
        id: "export",
        label: "Deforum export",
        description: "Build the Deforum settings package from Render.",
        destination: "render",
        requiredPrerequisites: ["deforumExport"],
      },
      {
        id: "outputs",
        label: "Inspect export",
        description: "Reveal and verify the registered Deforum export.",
        destination: "outputs",
        requiredPrerequisites: ["deforumExport"],
      },
    ],
    requiredCapabilities: ["backend"],
    optionalCapabilities: ["edmgCore", "ffmpeg"],
    requiredPrerequisites: ["project", "plan"],
    action: { label: "Continue Deforum workflow", destination: "workspace" },
    destructive: false,
    status: "supported",
  },
];
