import type { StudioForgeTemplate } from "./types";

export const STUDIO_FORGE_TEMPLATES: StudioForgeTemplate[] = [
  {
    id: "render-queue-dashboard",
    name: "Render Queue Dashboard",
    kind: "panel",
    description: "Preview an additive queue monitor that summarizes internal jobs, retries, and output readiness.",
    requiredCapabilities: ["backend", "internalRenderer"],
    optionalCapabilities: ["comfyui", "ffmpeg"],
    requiredPrerequisites: ["project"],
    action: { label: "Open Render Queue", destination: "queue" },
    destructive: false,
    status: "supported",
  },
  {
    id: "setup-health-panel",
    name: "Setup Health Panel",
    kind: "panel",
    description: "Summarize Setup Wizard runtime health without changing installers, storage roots, or runtime processes.",
    requiredCapabilities: ["backend", "ffmpeg"],
    optionalCapabilities: ["ollama", "comfyui", "edmgCore"],
    action: { label: "Open Setup", destination: "setup" },
    destructive: false,
    status: "supported",
  },
  {
    id: "model-pack-card",
    name: "Model Pack Card",
    kind: "modelProfile",
    description: "Preview capability-aware model summaries for local Ollama, internal renderer models, and optional sidecars.",
    requiredCapabilities: ["backend"],
    optionalCapabilities: ["ollama", "comfyui", "edmgCore"],
    action: { label: "Open Models", destination: "models" },
    destructive: false,
    status: "supported",
  },
  {
    id: "audio-to-video-recipe",
    name: "Audio to Video Recipe",
    kind: "workflow",
    description: "Outline the canonical Studio path from audio analysis through plan generation, rendering, and assembly.",
    requiredCapabilities: ["backend", "internalRenderer", "ffmpeg"],
    optionalCapabilities: ["ollama", "edmgCore"],
    requiredPrerequisites: ["project", "audio"],
    action: { label: "Open Workspace", destination: "workspace" },
    destructive: false,
    status: "supported",
  },
  {
    id: "comfyui-motion-recipe",
    name: "ComfyUI Motion Recipe",
    kind: "workflow",
    description: "Preview a motion-oriented branch that keeps ComfyUI optional and leaves the default internal renderer untouched.",
    requiredCapabilities: ["backend"],
    optionalCapabilities: ["comfyui", "ffmpeg"],
    requiredPrerequisites: ["project", "plan"],
    action: { label: "Open Render", destination: "render" },
    destructive: false,
    status: "supported",
  },
  {
    id: "deforum-export-recipe",
    name: "Deforum Export Recipe",
    kind: "renderPreset",
    description: "Show how a future builder could guide users toward Deforum export without mutating project state in v1.",
    requiredCapabilities: ["backend"],
    optionalCapabilities: ["edmgCore", "ffmpeg"],
    requiredPrerequisites: ["project", "plan"],
    action: { label: "Open Deforum Export", destination: "render" },
    destructive: false,
    status: "supported",
  },
];
