"""Public, versioned contracts shared across Studio domains."""

from .compat import (
    adapt_legacy_cue,
    adapt_legacy_director_document,
    adapt_legacy_editor_command,
    adapt_legacy_job,
    adapt_legacy_project,
    adapt_legacy_render_plan,
    restore_legacy_director_document,
    restore_legacy_editor_command,
)
from .v1 import (
    CONTRACT_MODELS,
    CONTRACT_SCHEMA_VERSION,
    ArtifactManifestContract,
    CapabilityContract,
    CommandContract,
    CommandHistoryStateContract,
    CreativeIntentContract,
    CueContract,
    DirectorDocumentContract,
    HardwareProfileContract,
    JobContract,
    MusicGraphContract,
    ProjectContract,
    RenderPlanContract,
    contract_schema_bundle,
)

__all__ = [
    "CONTRACT_MODELS",
    "CONTRACT_SCHEMA_VERSION",
    "ArtifactManifestContract",
    "CapabilityContract",
    "CommandContract",
    "CommandHistoryStateContract",
    "CreativeIntentContract",
    "CueContract",
    "DirectorDocumentContract",
    "HardwareProfileContract",
    "JobContract",
    "MusicGraphContract",
    "ProjectContract",
    "RenderPlanContract",
    "adapt_legacy_cue",
    "adapt_legacy_director_document",
    "adapt_legacy_editor_command",
    "adapt_legacy_job",
    "adapt_legacy_project",
    "adapt_legacy_render_plan",
    "restore_legacy_director_document",
    "restore_legacy_editor_command",
    "contract_schema_bundle",
]
